name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ESLINT_USE_FLAT_CONFIG: false

    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Lint the project
        run: yarn lint

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: "../../Dockerfile"
          tags: lukie133/webapp:latest
          push: false
